# Generated by Django 5.2.5 on 2025-09-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimarePret',
        ),
    ]
